### ISSUE TITLE
GradientBoxView not inheriting parents' widthRequest

### ISSUE THREAD

**Issue by reense** [DevsDNA/GradientBoxView#1]
Hi!
I've used this package for a while now, but since the latest Xamarin.Forms update the gradient boxview does not keep it's desired width/height, it renders to the whole canvas.

Any idea on how to fix this?

**Comment by MarcosCobena** [comment]
Hi @reense,

Thanks for using it! And sorry for the delay in answering.

I've just used the control in XF 3.x and it works as expected. Could you please share some code which demoes the bug? If you could attach a ZIP we can just open and run would be great.

Thanks again!

**Comment by reense** [comment]
I've fixed this problem already. Thanks for asking!

**Comment by MarcosCobena** [comment]
No problem, let's know any other you may have —hope none :-)

Thanks for coming back.
